# Generated by Django 2.0.6 on 2018-07-09 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regno', models.IntegerField()),
                ('attendance', models.IntegerField(default=111)),
                ('date', models.DateTimeField()),
                ('sub_name', models.CharField(max_length=15)),
                ('teac_id', models.IntegerField()),
                ('listening_skills', models.IntegerField()),
                ('learning_attitude', models.IntegerField()),
                ('assignment_submission', models.IntegerField()),
                ('communication_skills', models.IntegerField()),
                ('collaboration_with_students', models.IntegerField()),
                ('others_if_mention', models.CharField(default='Nothing', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regno', models.IntegerField()),
                ('exam_type', models.CharField(max_length=25)),
                ('year', models.IntegerField()),
                ('s1', models.IntegerField()),
                ('s2', models.IntegerField()),
                ('s3', models.IntegerField()),
                ('s4', models.IntegerField()),
                ('s5', models.IntegerField()),
                ('s6', models.IntegerField()),
                ('s7', models.IntegerField()),
                ('s8', models.IntegerField()),
                ('s9', models.IntegerField()),
                ('s10', models.IntegerField()),
                ('avg', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regno', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('dept_id', models.IntegerField()),
                ('year', models.IntegerField()),
                ('section', models.CharField(max_length=3)),
                ('student_mobile', models.IntegerField()),
                ('student_email', models.EmailField(max_length=254)),
                ('parent_email', models.EmailField(max_length=254)),
                ('parent_mobile', models.IntegerField()),
            ],
        ),
    ]
